### ISSUE TITLE
Consider archiving of this repository

### ISSUE THREAD

**Issue by CodeGat** [ACCESS-NRI/reproducibility#30]
With the removal of the reusable workflows within this repository, as part of https://github.com/ACCESS-NRI/reproducibility/pull/29, we should consider this repository archivable. We can move the remaining issues to https://github.com/ACCESS-NRI/model-config-tests/issues

Pinging @aidanheerdegen for his opinions of this matter (not urgent)

**Comment by aidanheerdegen** [comment]
I have closed outdated issues and moved ones we want to keep to other repos and will now archive.
