### ISSUE TITLE
Move Generic Code out of `access-om2-configs` into `reproducibility`

### ISSUE THREAD

**Issue by CodeGat** [ACCESS-NRI/reproducibility#8]
After working on this solution for a while, it has been noted that there is more code that can come out of `access-om2-configs` as it sufficiently generic to be used for all model configurations. See https://github.com/ACCESS-NRI/access-om2-configs/pull/2#discussion_r1473865871

This issue can serve as a hub for finding snippets of code from `access-om2-configs` that are sufficiently generic (or can be made sufficiently generic) to be placed in this repository. 

**Aspects to be moved into this repository**
* Downloading of checksum, parsing test results, notifying of failure or success
* Notification of scheduled checksum failure via issue creation

**Comment by dougiesquire** [comment]
Could the [reproducibility pytests](https://github.com/ACCESS-NRI/access-om2-configs/tree/main/test) be moved here or even into their own repo? It looks like they've been written in a way that can be easy extended to other models.

**Comment by aidanheerdegen** [comment]
> Could the [reproducibility pytests](https://github.com/ACCESS-NRI/access-om2-configs/tree/main/test) be moved here or even into their own repo? It looks like they've been written in a way that can be easy extended to other models.

IIRC the original idea was to keep the tests as part of the config repo but deployed to a `conda` env to make accessing them more straightforward. If they needed to be used in more than one repository then it might make more sense for them to be in a separate repo.

**Comment by dougiesquire** [comment]
> IIRC the original idea was to keep the tests as part of the config repo but deployed to a conda env to make accessing them more straightforward. If they needed to be used in more than one repository then it might make more sense for them to be in a separate repo

Okay. I only ask because it looks like the code has been written to make it easy to add other models, and I think most of what's there could be used with ACCESS-OM3

**Comment by aidanheerdegen** [comment]
> Okay. I only ask because it looks like the code has been written to make it easy to add other models, and I think most of what's there could be used with ACCESS-OM3

Well that is another reason to make a separate repo, if the bulk of the code is applicable to more than one model.

Opinions @jo-basevi @CodeGat ?

**Comment by CodeGat** [comment]
A separate repo for different pytests, you mean? I can get behind that. If we can package up the test code into packages or something in that repo and just reference the packages that would be the best.

**Comment by dougiesquire** [comment]
I was imagining a single Python package for extracting and testing output from various models. E.g. we could add an `accessom3` class to https://github.com/ACCESS-NRI/access-om2-configs/tree/main/test/models. I sort of started [something similar a while ago](https://github.com/dougiesquire/morte), but I didn't make it far before other things took priority.

**Comment by aidanheerdegen** [comment]
I discussed [morte](https://github.com/dougiesquire/morte) with @jo-basevi when this work was started, and we did think we could maybe use it as the basis of an external test suite thingo. Still could be if you think there is utility in that approach. I like the name very much, but maybe something more utilitarian (`access-config-tests`?) might be more understandable?

**Comment by dougiesquire** [comment]
> we did think we could maybe use it as the basis of an external test suite thingo. Still could be if you think there is utility in that approach.

I wasn't meaning to suggest that we should use morte (or even the name). I maybe haven't spent enough time looking at https://github.com/ACCESS-NRI/access-om2-configs/tree/main/test, but isn't that pretty much an "external test suite thingo" already (at least for Payu-run models)? It's written in a way that looks very easy to extend to other models (which is great!). It just needs to be moved out of `access-om2-configs`.

Why do I have that feeling that we're all saying the same thing, but in slightly different ways...

**Comment by aidanheerdegen** [comment]
> isn't that pretty much an "external test suite thingo" already (at least for Payu-run models)? It's written in a way that looks very easy to extend to other models (which is great!). It just needs to be moved out of `access-om2-configs`.

Do you have a timeline for this? It might be good from our point of view to wait a week or so until we've got the tests all working  before we shift it out into a separate location. It would be a bit of a pain to make changes here and then have port them over to another repo. If you're in a hurry though, go ahead and we will manage.

**Comment by dougiesquire** [comment]
I'm not in a rush. For now, I've just copied the contents of `access-om2-configs/test` to my own fork of the ACCESS-OM3 `MOM6-CICE6` config repo and extended that for ACCESS-OM3. That will suffice for now while I work out how to utilise/copy all the associated workflows you guys set up.

Or... if those workflows are also in flux, I can wait until they're bedded down?

**Comment by aidanheerdegen** [comment]
> I'm not in a rush. For now, I've just copied the contents of `access-om2-configs/test` to my own fork of the ACCESS-OM3 `MOM6-CICE6` config repo and extended that for ACCESS-OM3. That will suffice for now while I work out how to utilise/copy all the associated workflows you guys set up.
> 
> Or... if those workflows are also in flux, I can wait until they're bedded down?

It's all a bit fluxy TBH.

**Comment by CodeGat** [comment]
Closing this issue as code will be moved into `ACCESS-NRI/model-config-tests` instead of here. See linked issue: https://github.com/ACCESS-NRI/model-config-tests/issues/23
